services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: unless-stopped
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init:/init:ro
    # If you're on Windows ARM, uncomment next line to force emulation
    # platform: linux/amd64

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql_db_init
    depends_on:
      - sqlserver
    restart: "no"
    volumes:
      - ./init:/init:ro
    environment:
      - ACCEPT_EULA=Y
    entrypoint: ["/bin/bash","-c",
      "for i in {1..60}; do /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' && break || sleep 2; done;        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SA_PASSWORD} -v DBNAME=${MSSQL_DATABASE} APPUSER=${MSSQL_USER} APPPASS=${MSSQL_PASSWORD} -i /init/01-init.sql"
    ]

volumes:
  mssql_data:
